### ISSUE TITLE
[BUG] - Bare-Metal wrong airootfs.sfs and vmlinuz-linux paths for ISO from cloned repository

### ISSUE THREAD

**Issue by D3vil0p3r** [axyl-os/axyl-iso#107]
Hello,
I generated the ISO by Archiso from cloning `axyl-iso` repository.

Let's start saying that `unpackfs.sfs` Calamares module has the following content. Focus on `airootfs.sfs` and `vmlinuz-linux` paths:
```
unpack:
    -   source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux"
        sourcefs: "file"
        destination: "/boot/vmlinuz-linux"
```
When I burn the ISO inside a USB key, and I boot the system by the USB key, I noted that:
* `airootfs.sfs` file will be in `<mounted-path-of-usb-key>/arch/x86_64/` instead of `/run/archiso/bootmnt/arch/x86_64/`
* `vmlinuz-linux` file will be in `<mounted-path-of-usb-key>/arch/boot/x86_64/` instead of `/run/archiso/bootmnt/arch/boot/x86_64/`

It does not happen when I mount the .iso file directly on a Virtual Machine (i.e., in WMware Workstation software).

It does not occur with the latest release `axyl-2022.08.10-x86_64.iso` file, it happens only by cloning the repository (that should contain the latest files). Why this? Is there a way to mount automatically `airootfs.sfs` and `vmlinuz-linux` to `/run/archiso/bootmnt/`?

To reproduce:
1. Clone the repository: `git clone https://github.com/axyl-os/axyl-iso`
2. `cd axyl-iso/installation-scripts`
3. `./re-build.sh`
4. At the end, when the ISO is created, burn it in a USB key (I used Rufus in Windows for burning it)
5. Plug in the USB key, reboot the system and boot on it
6. Inside the Axyl ISO system, execute `ls /run/archiso`. The folder `bootmnt` is not there.

It means that, if you will try to install the system by Calamares, `unpackfs` module will fail because won't find the `airootfs.sfs` and `vmlinuz-linux` files specified in its configuration module.
PS: if you test it, remember to recompile axyl-calamares because it expects libboost_python310 at 1.79 version but the latest is 1.80.
